trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc

- script: |
    npm install
  displayName: 'npm install'

- script: >
    npx -p semantic-release
    -p @semantic-release/git
    -p semantic-release-ado
    semantic-release
  env: { GH_TOKEN: $(GitHubToken) }
  displayName: 'Semantic release'